title: Arxiv Papers Daily
description: Automatically Update Arxiv Papers Daily using Github Actions (Update Every 8th hours)
show_downloads: true

github:
  zip_url: https://github.com/Jasper0420/arxiv-papers-daily
  another_url: https://github.com/Jasper0420/arxiv-papers-daily

## add remote theme
remote_theme: jekyll/minima@v2.5.1

# minima:
skin: dark
social_links:
  twitter: Jasper0420
  github: Jasper0420

plugins:
 - jekyll-remote-theme # add this line to the plugins list if you already have one
 - jekyll-feed
 - jekyll-seo-tag
